README.md
package-lock.json
vercel.json

Deploy Storybook

---

src/PCBViewer.tsx

Display error on the screen

---

.storybook/main.ts
.storybook/preview.ts
package-lock.json
package.json
src/PCBViewer.tsx
src/components/CanvasElementsRenderer.tsx
src/components/CanvasPrimitiveRenderer.tsx
src/components/ContextProviders.tsx
src/components/DimensionOverlay.tsx
src/components/MouseElementTracker.tsx
src/components/ToolbarOverlay.tsx
src/global-store.ts
src/lib/Drawer.ts
src/stories/coordinate-flip.stories.tsx
src/stories/multi-layer-circuit.stories.tsx

https://github.com/tscircuit/tscircuit/issues/79

Version 1.3: Flipped Y Axis, PCB Trace Errors, Layer Selection

---

package-lock.json
package.json
src/PCBViewer.tsx
src/components/CanvasElementsRenderer.tsx
src/components/CanvasPrimitiveRenderer.tsx
src/components/EditOverlay.tsx
src/components/ElementOverlayBox.tsx
src/components/ToolbarOverlay.tsx
src/global-store.ts
src/lib/apply-edit-events.ts
src/lib/edit-events.ts
src/stories/trace-error.stories.tsx

- **add verbose story for trace error**
- **Dragging initial**

Dragging Footprints

---

src/components/DimensionOverlay.tsx

Closes https://github.com/tscircuit/pcb-viewer/issues/11

Fix dimension tool being triggered outside of component hover or focus

---

src/lib/Drawer.ts
src/lib/convert-element-to-primitive.ts
src/lib/draw-primitives.ts
src/lib/types.ts
src/stories/silkscreen/silkscreen-oval.stories.tsx

Closes - https://github.com/tscircuit/tscircuit/issues/208#issuecomment-2197187565

feat: support for primitive added

---

src/lib/convert-element-to-primitive.ts

@seveibar Update the syntax in pcb-viewer too

syntax update

---

src/lib/Drawer.ts
src/lib/convert-element-to-primitive.ts
src/lib/draw-primitives.ts
src/lib/types.ts
src/stories/silkscreen/silkscreen-pill.stories.tsx

Issue - https://github.com/tscircuit/tscircuit/issues/208

add pill story

---

src/lib/convert-element-to-primitive.ts
src/stories/plated_hole_pill_shape.stories.tsx
src/stories/simple-resistor.stories.tsx

Closes issue - https://github.com/tscircuit/tscircuit/issues/215

Feat  plated hole oval shape

---

src/lib/convert-element-to-primitive.ts
src/stories/plated_hole_pill_shape.stories.tsx

closes - https://github.com/tscircuit/tscircuit/issues/215

added pill shape

---

.github/workflows/npm-build.yml
src/lib/edit-events.ts

- **fix build issue**
- **add npm build workflows**

Add npm build workflow and fix build error

---

biome.json
package-lock.json
src/PCBViewer.tsx
src/components/CanvasElementsRenderer.tsx
src/components/ContextProviders.tsx
src/components/ErrorOverlay.tsx
src/components/RatsNestOverlay.tsx
src/components/ToolbarOverlay.tsx
src/global-store.ts

- **introduce rats nest toggle**
- **allow setting pcb viewer initial state**
https://github.com/user-attachments/assets/b2e2461a-257d-4855-b9e2-6b717ef6c024
fixes https://github.com/tscircuit/tscircuit/issues/269

Introduce rats nest toggle, introduce `initialState` prop to PCBViewer

---

src/components/EditTraceHintOverlay.tsx
src/stories/tracehint.stories.tsx

feat: add the buldge in the trace

---

package-lock.json
package.json
src/components/EditTraceHintOverlay.tsx
src/lib/Drawer.ts
src/lib/convert-element-to-primitive.ts
src/lib/draw-primitives.ts
src/lib/types.ts
src/lib/util/expand-stroke.ts
src/stories/tracehint.stories.tsx

Closes - #41 
Have added this extra trace point to show the polygon.
https://github.com/user-attachments/assets/284fc1cc-f023-4287-8189-bfd5e32b8fb7

feat: Render inside Trace

---

package-lock.json
package.json
src/lib/convert-element-to-primitive.ts
src/stories/board.stories.tsx

Added pcb_board outline feature and tests

---

package-lock.json
package.json
src/lib/Drawer.ts
src/lib/convert-element-to-primitive.ts
src/lib/draw-primitives.ts
src/lib/types.ts

feat: pcb_keepout

---

package-lock.json
package.json
src/components/CanvasElementsRenderer.tsx
src/components/MouseElementTracker.tsx
src/lib/Drawer.ts
src/lib/convert-element-to-primitive.ts
src/lib/draw-primitives.ts
src/lib/get-net-list-map.ts
src/lib/types.ts
src/lib/util/if-sets-match-exactly.ts

Hover Highlights for Elements, add is_mouse_over to primitives

---

src/lib/Drawer.ts

highlight feature now works with multi-layer

---

package.json
src/PCBViewer.tsx
src/stories/simple-resistor.stories.tsx

Next step is to remove @tscircuit/builder entirely

Convert children rendering to core

---

biome.json
src/PCBViewer.tsx
src/lib/convert-element-to-primitive.ts
src/stories/silkscreen/silkscreen-path.stories.tsx

- **format and minor fix for silkscreen path story so that it renders**
- **remove console log**

Fix silkscreen path story

---

package-lock.json
src/components/CanvasElementsRenderer.tsx

is not assignable to parameter of type 'string'.
Type 'undefined' is not assignable to type 'string'.

fixed type error Argument of type 'string | undefined'

---

src/components/ElementOverlayBox.tsx

/closes #85
https://github.com/user-attachments/assets/733877f4-9f96-4f64-91d9-859d80e544c5

fixed  `ElementOverlayBox` text rotation

---

src/components/RatsNestOverlay.tsx
src/stories/trace-and-net.stories.tsx

https://github.com/user-attachments/assets/4702cfed-2151-4f73-813a-e896d6ee846a
/claim #91

rat's nest now shows lines between the closest ports

---

src/components/ElementOverlayBox.tsx
src/components/ToolbarOverlay.tsx
src/global-store.ts
src/lib/filter-traces-if-multiple.ts

/closes #109 
https://github.com/user-attachments/assets/e9a67721-04f9-4a45-a05e-d5a619ced971

Feature: Add View dropdown and enhance trace filtering algorithms to display only traces with max_length on hover

---

src/stories/repros/contribution-board-performance-test/contribution-board.stories.tsx
src/stories/repros/contribution-board-performance-test/useHS91L02W2C01.tsx
src/stories/repros/contribution-board-performance-test/usePICO.tsx
src/stories/repros/contribution-board-performance-test/useWS2812B_2020.tsx

/claim #108
my pc died to render this test lol

 contribution-board performance test

---

src/PCBViewer.tsx
src/components/CanvasElementsRenderer.tsx
src/components/DimensionOverlay.tsx
src/stories/board.stories.tsx
src/stories/click-to-enable-zoom.stories.tsx

/claim #103
fix #103 
https://github.com/user-attachments/assets/1cafce98-7712-48ba-a250-923dce68283c

Feat: Add Click to interact feature

---

src/lib/Drawer.ts
src/lib/colors.ts
src/stories/silkscreen/silkscreen-layer.stories.tsx
src/stories/silkscreen/silkscreen-pill.stories.tsx

/claim #126
/close #126
https://github.com/user-attachments/assets/ff5a9fe6-91aa-49b5-977a-f7ad2bc572c4

multi silkscreen layers support

---

src/PCBViewer.tsx

fixes https://github.com/tscircuit/pcb-viewer/issues/184

Fix initial transform

---

biome.json
bun.lock
package.json
src/PCBViewer.tsx
src/components/CanvasElementsRenderer.tsx
src/components/WarningGraphicsOverlay.tsx
src/lib/util/z-index-map.ts
src/stories/manual-edit-conflicts-highlight.stories.tsx

related https://github.com/tscircuit/tscircuit.com/issues/866

feat: add warning graphics overlay for manual edit conflicts 

---

src/components/CanvasElementsRenderer.tsx
src/components/ErrorOverlay.tsx
src/components/ToolbarOverlay.tsx
src/global-store.ts
src/stories/DRC-errors-highlight.stories.tsx

/claim #243
/closes #243 
https://github.com/user-attachments/assets/222942a1-e91c-4541-bf3e-a73d9b7e924e

Feat:Highlight DRC Errors (PcbTraceError)

---

src/PCBViewer.tsx

fixes #251 
closes #253 
/claim #251
https://github.com/user-attachments/assets/3a723599-46b0-4028-9576-244b55746299

fix: touch to interact work on mobile

---

src/PCBViewer.tsx
src/lib/util/z-index-map.ts

resolve https://github.com/tscircuit/tscircuit.com/issues/1029
https://github.com/user-attachments/assets/97b2a298-0da9-4542-8091-9fdcc23429dc

fix: increase zIndex in PCBViewer for improved overlay handling

---

src/examples/silkscreen/silkscreen-text-bottom-layer.fixture.tsx
src/lib/draw-primitives.ts

silkscreen text horizontally inverted in the bottom layer

---

src/lib/util/z-index-map.ts

fix(z-index): unable to access toolbar while errors are there

---

src/examples/plated_hole_rotated_pill_hole_with_rect_pad.fixture.tsx
src/lib/Drawer.ts
src/lib/convert-element-to-primitive.ts
src/lib/draw-primitives.ts
src/lib/types.ts

support pill hole & square pad pcb_plated_hole

---

src/global-store.ts
src/hooks/useLocalStorage.ts

feat(global-store): integrate local storage for PCB groups visibility
